-- Blog module — admin-authored posts, optionally drafted by AI.
-- Public-readable when published_at IS NOT NULL AND published_at <= now().
-- Admins (is_admin RPC) can read/write everything regardless of state.

create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content_md text not null default '',
  cover_image_url text,
  -- nullable = draft; non-null + <= now() = visible
  published_at timestamptz,
  -- True when the body was first generated by /api/admin/blog/generate (LLM
  -- draft). Editors can still revise it before publishing; the flag stays
  -- so we can audit AI-touched content if needed.
  ai_generated boolean not null default false,
  ai_prompt text,
  author text not null default 'Reine & Fils',
  reading_minutes int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_blog_posts_published_at
  on public.blog_posts (published_at desc nulls last);

create index if not exists idx_blog_posts_slug on public.blog_posts (slug);

-- RLS: public can read published rows only; admin RPC gates the rest.
alter table public.blog_posts enable row level security;

drop policy if exists "blog_posts_public_read" on public.blog_posts;
create policy "blog_posts_public_read"
  on public.blog_posts
  for select
  using (published_at is not null and published_at <= now());

drop policy if exists "blog_posts_admin_all" on public.blog_posts;
create policy "blog_posts_admin_all"
  on public.blog_posts
  for all
  using (public.is_admin())
  with check (public.is_admin());

-- updated_at auto-touch
create or replace function public.touch_blog_posts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_blog_posts_touch_updated_at on public.blog_posts;
create trigger trg_blog_posts_touch_updated_at
  before update on public.blog_posts
  for each row execute function public.touch_blog_posts_updated_at();
